services:
  hadoop:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9870:9870 # namenode port
      - 8088:8088 # resource manager port
      - 8042:8042 # yarn port
    volumes:
      - ../src/:/src/
